server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spring-security
  datasource:
    # URL connection to database (spring-security is database name)
    url: jdbc:mariadb://localhost:3306/db_spotify_clone
    # H2 sql Driver
    driver-class-name: org.mariadb.jdbc.Driver
    username: spotifyclonedev
    password: spotifyclone123
  jpa:
    # Provide database platform that is being used
    # database-platform:
    hibernate:
      # New database is created when application starts and destroyed when application is stopped
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    expiration: 60000
  refresh:
    expiration: 120000

